import type { Metadata } from "next";
import { Raleway } from "next/font/google";

const raleway = Raleway({
  preload: true,
  variable: "--font-raleway",
  subsets: ["latin"],
});

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable}`}>
      <body>{children}</body>
    </html>
  );
}
