import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "../styles/index.scss";
import { Toaster } from "react-hot-toast";
import { Toaster as ShadcnToaster } from "@/components/ui/toaster";

const raleway = Raleway({
  preload: true,
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable}`}>
      <body>
        {children}
        <Toaster position="bottom-right" reverseOrder={false} />
        <ShadcnToaster />
      </body>
    </html>
  );
}
